### Test 1: Register a new user (POST /api/auth/register/)
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
    "username": "rojogpt2",
    "email": "rojogpt2@gmail.com",
    "password": "password123"
}

###

### Test 2: Login to get JWT token (POST /api/auth/login/)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "rojogpt2",
    "password": "password123"
}
###

### Test 3: Get user profile (GET /api/auth/profile/) with JWT
GET http://127.0.0.1:8000/api/auth/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNzI0NTE3LCJpYXQiOjE3NDE3MjA5MTcsImp0aSI6ImRjMGUyM2MxZTUyZDRhYzk5ODIwNzg4NTg0ZmIzZTllIiwidXNlcl9pZCI6Mn0.Sv0FWDm9VVruKsa4p35UkRZZxZFv5HWoRcEqaYtIxcA
Content-Type: application/json

###

### Test 4: Logout (POST /api/auth/logout/) with JWT
POST http://127.0.0.1:8000/api/auth/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNzI0NTE3LCJpYXQiOjE3NDE3MjA5MTcsImp0aSI6ImRjMGUyM2MxZTUyZDRhYzk5ODIwNzg4NTg0ZmIzZTllIiwidXNlcl9pZCI6Mn0.Sv0FWDm9VVruKsa4p35UkRZZxZFv5HWoRcEqaYtIxcA
Content-Type: application/json

###

### Test 5: Reset Password (POST /api/auth/reset-password/)
POST http://127.0.0.1:8000/api/auth/reset-password/
Content-Type: application/json

{
    "email": "rojogpt2@gmail.com"
}
### Test 6: Login to get JWT token with new password(POST /api/auth/login/)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "rojogpt2",
    "password": "newpassword123"
}
###